// apps/api/src/fiscal/ciiu-rev4-ac.ts
//
// AUTO-GENERADO desde docs/data/ciiu-rev4-ac.csv. No editar a mano.
//
// Clasificación Industrial Internacional Uniforme revisión 4 adaptada para
// Colombia (CIIU Rev. 4 A.C., 2020), del DANE. Es la nomenclatura que usan la
// DIAN y las cámaras de comercio, así que va embebida y no en la base: es la
// misma para todas las firmas y no la edita nadie.
//
// Procedencia: estructura detallada del PDF oficial del DANE
// (dane.gov.co/files/acerca/Normatividad/resoluciones/2020/CIIU_Rev_4_AC.pdf).
// Verificada por tres vías, porque un PDF de 700 páginas se parsea mal en
// silencio: contra las notas explicativas del mismo documento (ninguna clase
// aparece allí que falte aquí), contra el buscador en vivo del DANE
// (clasificaciones.dane.gov.co/ciiu4-0) con 20 clases comprobadas una a una y
// 40 códigos inexistentes confirmados como tales, y con las pruebas de
// ciiu-rev4-ac.test.ts.
//
// 499 clases, secciones A a U.

export type ClaseCiiu = { codigo: string; descripcion: string; seccion: string };

export const SECCIONES_CIIU: Record<string, string> = {
  A: 'Agricultura, ganadería, caza, silvicultura y pesca',
  B: 'Explotación de minas y canteras',
  C: 'Industrias manufactureras',
  D: 'Suministro de electricidad, gas, vapor y aire acondicionado',
  E: 'Distribución de agua; evacuación y tratamiento de aguas residuales, gestión de desechos y actividades de saneamiento ambiental',
  F: 'Construcción',
  G: 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas',
  H: 'Transporte y almacenamiento',
  I: 'Alojamiento y servicios de comida',
  J: 'Información y comunicaciones',
  K: 'Actividades financieras y de seguros',
  L: 'Actividades inmobiliarias',
  M: 'Actividades profesionales, científicas y técnicas',
  N: 'Actividades de servicios administrativos y de apoyo',
  O: 'Administración pública y defensa; planes de seguridad social de afiliación obligatoria',
  P: 'Educación',
  Q: 'Actividades de atención de la salud humana y de asistencia social',
  R: 'Actividades artísticas, de entretenimiento y recreación',
  S: 'Otras actividades de servicios',
  T: 'Actividades de los hogares individuales en calidad de empleadores; actividades no diferenciadas de los hogares individuales como productores de bien es y servicios para uso propio',
  U: 'Actividades de organizaciones y entidades extraterritoriales',
};

export const CIIU_REV4_AC: ClaseCiiu[] = [
  { codigo: '0111', descripcion: 'Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas', seccion: 'A' },
  { codigo: '0112', descripcion: 'Cultivo de arroz', seccion: 'A' },
  { codigo: '0113', descripcion: 'Cultivo de hortalizas, raíces y tubérculos', seccion: 'A' },
  { codigo: '0114', descripcion: 'Cultivo de tabaco', seccion: 'A' },
  { codigo: '0115', descripcion: 'Cultivo de plantas textiles', seccion: 'A' },
  { codigo: '0119', descripcion: 'Otros cultivos transitorios n.c.p.', seccion: 'A' },
  { codigo: '0121', descripcion: 'Cultivode frutas tropicales y subtropicales', seccion: 'A' },
  { codigo: '0122', descripcion: 'Cultivo de plátano y banano', seccion: 'A' },
  { codigo: '0123', descripcion: 'Cultivo de café', seccion: 'A' },
  { codigo: '0124', descripcion: 'Cultivo de caña de azúcar', seccion: 'A' },
  { codigo: '0125', descripcion: 'Cultivode flor de corte', seccion: 'A' },
  { codigo: '0126', descripcion: 'Cultivo de palma para aceite (palma africana)y otros frutos oleaginosos', seccion: 'A' },
  { codigo: '0127', descripcion: 'Cultivo de plantas con las que se preparan bebidas', seccion: 'A' },
  { codigo: '0128', descripcion: 'Cultivo de especias y de plantas aromáticas y medicinales', seccion: 'A' },
  { codigo: '0129', descripcion: 'Otros cultivos permanentes n.c.p.', seccion: 'A' },
  { codigo: '0130', descripcion: 'Propagación de plantas (actividades de los viveros, excepto viveros forestales)', seccion: 'A' },
  { codigo: '0141', descripcion: 'Cría de ganado bovino y bufalino', seccion: 'A' },
  { codigo: '0142', descripcion: 'Cría de caballos y otros equinos', seccion: 'A' },
  { codigo: '0143', descripcion: 'Cría de ovejas y cabras', seccion: 'A' },
  { codigo: '0144', descripcion: 'Cría de ganado porcino', seccion: 'A' },
  { codigo: '0145', descripcion: 'Cría de aves de corral', seccion: 'A' },
  { codigo: '0149', descripcion: 'Cría de otros animales n.c.p.', seccion: 'A' },
  { codigo: '0150', descripcion: 'Explotación mixta (agrícola y pecuaria)', seccion: 'A' },
  { codigo: '0161', descripcion: 'Actividades de apoyo a la agricultura', seccion: 'A' },
  { codigo: '0162', descripcion: 'Actividades de apoyo a la ganadería', seccion: 'A' },
  { codigo: '0163', descripcion: 'Actividades posteriores a la cosecha', seccion: 'A' },
  { codigo: '0164', descripcion: 'Tratamiento de semillas para propagación', seccion: 'A' },
  { codigo: '0170', descripcion: 'Caza ordinaria y mediante trampas y actividades de servicios conexas', seccion: 'A' },
  { codigo: '0210', descripcion: 'Silvicultura y otras actividades forestales', seccion: 'A' },
  { codigo: '0220', descripcion: 'Extracción de madera', seccion: 'A' },
  { codigo: '0230', descripcion: 'Recolección de productos forestales diferentes a la madera', seccion: 'A' },
  { codigo: '0240', descripcion: 'Servicios de apoyo a la silvicultura', seccion: 'A' },
  { codigo: '0311', descripcion: 'Pesca marítima', seccion: 'A' },
  { codigo: '0312', descripcion: 'Pesca de agua dulce', seccion: 'A' },
  { codigo: '0321', descripcion: 'Acuicultura marítima', seccion: 'A' },
  { codigo: '0322', descripcion: 'Acuicultura de agua dulce', seccion: 'A' },
  { codigo: '0510', descripcion: 'Extracción de hulla (carbón de piedra)', seccion: 'B' },
  { codigo: '0520', descripcion: 'Extracción de carbón lignito', seccion: 'B' },
  { codigo: '0610', descripcion: 'Extracción de petróleo crudo', seccion: 'B' },
  { codigo: '0620', descripcion: 'Extracción de gas natural', seccion: 'B' },
  { codigo: '0710', descripcion: 'Extracción de minerales de hierro', seccion: 'B' },
  { codigo: '0721', descripcion: 'Extracción de minerales de uranio y de torio', seccion: 'B' },
  { codigo: '0722', descripcion: 'Extracción de oro y otros metales preciosos', seccion: 'B' },
  { codigo: '0723', descripcion: 'Extracción de minerales de níquel', seccion: 'B' },
  { codigo: '0729', descripcion: 'Extracción de otros minerales metalíferos no ferrosos n.c.p.', seccion: 'B' },
  { codigo: '0811', descripcion: 'Extracción de piedra, arena, arcillas comunes, yeso y anhidrita', seccion: 'B' },
  { codigo: '0812', descripcion: 'Extracción de arcillas de uso industrial, caliza, caolín y bentonitas', seccion: 'B' },
  { codigo: '0820', descripcion: 'Extracción de esmeraldas, piedras preciosas y semipreciosas', seccion: 'B' },
  { codigo: '0891', descripcion: 'Extracción de minerales para la fabricación de abonos y productos químicos', seccion: 'B' },
  { codigo: '0892', descripcion: 'Extracción de halita (sal)', seccion: 'B' },
  { codigo: '0899', descripcion: 'Extracción de otros minerales no metálicos n.c.p.', seccion: 'B' },
  { codigo: '0910', descripcion: 'Actividades de apoyo para la extracción de petróleo y de gas natural', seccion: 'B' },
  { codigo: '0990', descripcion: 'Actividades de apoyo para otras actividades de explotación de minas y canteras', seccion: 'B' },
  { codigo: '1011', descripcion: 'Procesamiento y conservación de carne y productos cárnicos', seccion: 'C' },
  { codigo: '1012', descripcion: 'Procesamiento y conservación de pescados, crustáceos y moluscos', seccion: 'C' },
  { codigo: '1020', descripcion: 'Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos', seccion: 'C' },
  { codigo: '1030', descripcion: 'Elaboración de aceites y grasas de origen vegetal y animal', seccion: 'C' },
  { codigo: '1040', descripcion: 'Elaboración de productos lácteos', seccion: 'C' },
  { codigo: '1051', descripcion: 'Elaboración de productos de molinería', seccion: 'C' },
  { codigo: '1052', descripcion: 'Elaboración de almidones y productos derivados del almidón', seccion: 'C' },
  { codigo: '1061', descripcion: 'Trilla de café', seccion: 'C' },
  { codigo: '1062', descripcion: 'Descafeinado, tostión y molienda del café', seccion: 'C' },
  { codigo: '1063', descripcion: 'Otros derivados del café', seccion: 'C' },
  { codigo: '1071', descripcion: 'Elaboración y refinación de azúcar', seccion: 'C' },
  { codigo: '1072', descripcion: 'Elaboración de panela', seccion: 'C' },
  { codigo: '1081', descripcion: 'Elaboración de productos de panadería', seccion: 'C' },
  { codigo: '1082', descripcion: 'Elaboración de cacao, chocolate y productos de confitería', seccion: 'C' },
  { codigo: '1083', descripcion: 'Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares', seccion: 'C' },
  { codigo: '1084', descripcion: 'Elaboración de comidas y platos preparados', seccion: 'C' },
  { codigo: '1089', descripcion: 'Elaboración de otros productos alimenticios n.c.p.', seccion: 'C' },
  { codigo: '1090', descripcion: 'Elaboración de alimentos preparados para animales', seccion: 'C' },
  { codigo: '1101', descripcion: 'Destilación, rectificación y mezcla de bebidas alcohólicas', seccion: 'C' },
  { codigo: '1102', descripcion: 'Elaboración de bebidas fermentadas no destiladas', seccion: 'C' },
  { codigo: '1103', descripcion: 'Producción de malta, elaboración de cervezas y otras bebidas malteadas', seccion: 'C' },
  { codigo: '1104', descripcion: 'Elaboración de bebidas no alcohólicas, producción de aguas minerales y otras aguas embotelladas', seccion: 'C' },
  { codigo: '1200', descripcion: 'Elaboración de productos de tabaco', seccion: 'C' },
  { codigo: '1311', descripcion: 'Preparación e hilatura de fibras textiles', seccion: 'C' },
  { codigo: '1312', descripcion: 'Tejeduría de productos textiles', seccion: 'C' },
  { codigo: '1313', descripcion: 'Acabado de productos textiles', seccion: 'C' },
  { codigo: '1391', descripcion: 'Fabricación de tejidos de punto y ganchillo', seccion: 'C' },
  { codigo: '1392', descripcion: 'Confección de artículos con materiales textiles, excepto prendas de vestir', seccion: 'C' },
  { codigo: '1393', descripcion: 'Fabricación de tapetes y alfombras para pisos', seccion: 'C' },
  { codigo: '1394', descripcion: 'Fabricación de cuerdas, cordeles, cables, bramantes y redes', seccion: 'C' },
  { codigo: '1399', descripcion: 'Fabricación de otros artículos textiles n.c.p.', seccion: 'C' },
  { codigo: '1410', descripcion: 'Confección de prendas de vestir, excepto prendas de piel', seccion: 'C' },
  { codigo: '1420', descripcion: 'Fabricación de artículos de piel', seccion: 'C' },
  { codigo: '1430', descripcion: 'Fabricación de artículos de punto y ganchillo', seccion: 'C' },
  { codigo: '1511', descripcion: 'Curtido y recurtido de cueros; recurtido y teñido de pieles.', seccion: 'C' },
  { codigo: '1512', descripcion: 'Fabricación de artículos de viaje, bolsos de mano y artículos similares elaborados en cuero, y fabricación de artículos de tala bartería y guarnicionería.', seccion: 'C' },
  { codigo: '1513', descripcion: 'Fabricación de artículos de viaje, bolsos de mano y artículos similares; artículos de talabartería y guarnicionería elaborados en otros materiales', seccion: 'C' },
  { codigo: '1521', descripcion: 'Fabricación de calzado de cuero y piel, con cualquier tipo de suela', seccion: 'C' },
  { codigo: '1522', descripcion: 'Fabricación de otros tipos de calzado, excepto calzado de cuero y piel', seccion: 'C' },
  { codigo: '1523', descripcion: 'Fabricación de partes del calzado', seccion: 'C' },
  { codigo: '1610', descripcion: 'Aserrado, acepillado e impregnación de la madera', seccion: 'C' },
  { codigo: '1620', descripcion: 'Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados, tableros laminados, tableros de partícula s y otros tableros y paneles', seccion: 'C' },
  { codigo: '1630', descripcion: 'Fabricación de partes y piezas de madera, de carpintería y ebanistería para la construcción', seccion: 'C' },
  { codigo: '1640', descripcion: 'Fabricación de recipientes de madera', seccion: 'C' },
  { codigo: '1690', descripcion: 'Fabricación de otros productos de madera; fabricación de artículo s de corcho, cestería y espartería', seccion: 'C' },
  { codigo: '1701', descripcion: 'Fabricación de pulpas (pastas) celulósicas; papel y cartón', seccion: 'C' },
  { codigo: '1702', descripcion: 'Fabricación de papel y cartón ondulado (corrugado); fabricación de envases, empaques y de embalajes de papel y cartón.', seccion: 'C' },
  { codigo: '1709', descripcion: 'Fabricación de otros artículos de papel y cartón', seccion: 'C' },
  { codigo: '1811', descripcion: 'Actividades de impresión', seccion: 'C' },
  { codigo: '1812', descripcion: 'Actividades de servicios relacionados con la impresión', seccion: 'C' },
  { codigo: '1820', descripcion: 'Producción de copias a partir de grabaciones originales', seccion: 'C' },
  { codigo: '1910', descripcion: 'Fabricación de productos de hornos de coque', seccion: 'C' },
  { codigo: '1921', descripcion: 'Fabricación de productos de la refinación del petróleo', seccion: 'C' },
  { codigo: '1922', descripcion: 'Actividad de mezcla de combustibles', seccion: 'C' },
  { codigo: '2011', descripcion: 'Fabricación de sustancias y productos químicos básicos', seccion: 'C' },
  { codigo: '2012', descripcion: 'Fabricación de abonos y compuestos inorgánicos nitrogenados', seccion: 'C' },
  { codigo: '2013', descripcion: 'Fabricación de plásticos en formas primarias', seccion: 'C' },
  { codigo: '2014', descripcion: 'Fabricación de caucho sintético en formas primarias', seccion: 'C' },
  { codigo: '2021', descripcion: 'Fabricación de plaguicidas y otros productos químicos de uso agropecuario', seccion: 'C' },
  { codigo: '2022', descripcion: 'Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas', seccion: 'C' },
  { codigo: '2023', descripcion: 'Fabricación de jabones y detergentes, preparados para limpiar y pulir; perfumes y preparados de tocador', seccion: 'C' },
  { codigo: '2029', descripcion: 'Fabricación de otros productos químicos n.c.p.', seccion: 'C' },
  { codigo: '2030', descripcion: 'Fabricación de fibras sintéticas y artificiales', seccion: 'C' },
  { codigo: '2100', descripcion: 'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico', seccion: 'C' },
  { codigo: '2211', descripcion: 'Fabricación de llantas y neumáticos de caucho', seccion: 'C' },
  { codigo: '2212', descripcion: 'Reencauche de llantas usadas', seccion: 'C' },
  { codigo: '2219', descripcion: 'Fabricación de formas básicas de caucho y otros productos de caucho n.c.p.', seccion: 'C' },
  { codigo: '2221', descripcion: 'Fabricación de formas básicas de plástico', seccion: 'C' },
  { codigo: '2229', descripcion: 'Fabricación de artículos de plástico n.c.p.', seccion: 'C' },
  { codigo: '2310', descripcion: 'Fabricación de vidrio y productos de vidrio', seccion: 'C' },
  { codigo: '2391', descripcion: 'Fabricación de productos refractarios', seccion: 'C' },
  { codigo: '2392', descripcion: 'Fabricación de materiales de arcilla para la construcción', seccion: 'C' },
  { codigo: '2393', descripcion: 'Fabricación de otros productos de cerámica y porcelana', seccion: 'C' },
  { codigo: '2394', descripcion: 'Fabricación de cemento, cal y yeso', seccion: 'C' },
  { codigo: '2395', descripcion: 'Fabricación de artículos de hormigón, cemento y yeso', seccion: 'C' },
  { codigo: '2396', descripcion: 'Corte, tallado y acabado de la piedra', seccion: 'C' },
  { codigo: '2399', descripcion: 'Fabricación de otros productos minerales no metálicos n.c.p.', seccion: 'C' },
  { codigo: '2410', descripcion: 'Industrias básicas de hierro y de acero', seccion: 'C' },
  { codigo: '2421', descripcion: 'Industrias básicas de metales preciosos', seccion: 'C' },
  { codigo: '2429', descripcion: 'Industrias básicas de otros metales no ferrosos', seccion: 'C' },
  { codigo: '2431', descripcion: 'Fundición de hierro y de acero', seccion: 'C' },
  { codigo: '2432', descripcion: 'Fundición de metales no ferrosos', seccion: 'C' },
  { codigo: '2511', descripcion: 'Fabricación de productos metálicos para uso estructural', seccion: 'C' },
  { codigo: '2512', descripcion: 'Fabricación de tanques, depósitos y recipientes de metal, excepto los utilizados para el envase o transporte de mercancías', seccion: 'C' },
  { codigo: '2513', descripcion: 'Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central', seccion: 'C' },
  { codigo: '2520', descripcion: 'Fabricación de armas y municiones', seccion: 'C' },
  { codigo: '2591', descripcion: 'Forja, prensado, estampado y laminado de metal; pulvimetalurgia', seccion: 'C' },
  { codigo: '2592', descripcion: 'Tratamiento y revestimiento de metales; mecanizado', seccion: 'C' },
  { codigo: '2593', descripcion: 'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería', seccion: 'C' },
  { codigo: '2599', descripcion: 'Fabricación de otros productos elaborados de metal n.c.p.', seccion: 'C' },
  { codigo: '2610', descripcion: 'Fabricación de componentes y tableros electrónicos', seccion: 'C' },
  { codigo: '2620', descripcion: 'Fabricación de computadoras y de equipo periférico', seccion: 'C' },
  { codigo: '2630', descripcion: 'Fabricación de equipos de comunicación', seccion: 'C' },
  { codigo: '2640', descripcion: 'Fabricación de aparatos electrónicos de consumo', seccion: 'C' },
  { codigo: '2651', descripcion: 'Fabricación de equipo de medición, prueba, navegación y control', seccion: 'C' },
  { codigo: '2652', descripcion: 'Fabricación de relojes', seccion: 'C' },
  { codigo: '2660', descripcion: 'Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico', seccion: 'C' },
  { codigo: '2670', descripcion: 'Fabricación de instrumentos ópticos y equipo fotográfico', seccion: 'C' },
  { codigo: '2680', descripcion: 'Fabricación de medios magnéticos y ópticos para almacenamiento de datos', seccion: 'C' },
  { codigo: '2711', descripcion: 'Fabricación de motores, generadores y transformadores eléctricos.', seccion: 'C' },
  { codigo: '2712', descripcion: 'Fabricación de aparatos de distribución y control de la energía eléctrica', seccion: 'C' },
  { codigo: '2720', descripcion: 'Fabricación de pilas, baterías y acumuladores eléctricos', seccion: 'C' },
  { codigo: '2731', descripcion: 'Fabricación de hilos y cables eléctricos y de fibra óptica', seccion: 'C' },
  { codigo: '2732', descripcion: 'Fabricación de dispositivos de cableado', seccion: 'C' },
  { codigo: '2740', descripcion: 'Fabricación de equipos eléctricos de iluminación', seccion: 'C' },
  { codigo: '2750', descripcion: 'Fabricación de aparatos de uso doméstico', seccion: 'C' },
  { codigo: '2790', descripcion: 'Fabricación de otros tipos de equipo eléctrico n.c.p.', seccion: 'C' },
  { codigo: '2811', descripcion: 'Fabricación de motores, turbinas, y partes para motores de combustión interna', seccion: 'C' },
  { codigo: '2812', descripcion: 'Fabricación de equipos de potencia hidráulica y neumática', seccion: 'C' },
  { codigo: '2813', descripcion: 'Fabricación de otras bombas, compresores, grifos y válvulas', seccion: 'C' },
  { codigo: '2814', descripcion: 'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión', seccion: 'C' },
  { codigo: '2815', descripcion: 'Fabricación de hornos, hogares y quemadores industriales', seccion: 'C' },
  { codigo: '2816', descripcion: 'Fabricación de equipo de elevación y manipulación', seccion: 'C' },
  { codigo: '2817', descripcion: 'Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipo periférico)', seccion: 'C' },
  { codigo: '2818', descripcion: 'Fabricación de herramientas manuales con motor', seccion: 'C' },
  { codigo: '2819', descripcion: 'Fabricación de otros tipos de maquinaria y equipo de uso general n.c.p.', seccion: 'C' },
  { codigo: '2821', descripcion: 'Fabricación de maquinaria agropecuaria y forestal', seccion: 'C' },
  { codigo: '2822', descripcion: 'Fabricación de máquinas formadoras de metal y de máquinas herramienta', seccion: 'C' },
  { codigo: '2823', descripcion: 'Fabricación de maquinaria para la metalurgia', seccion: 'C' },
  { codigo: '2824', descripcion: 'Fabricación de maquinaria para explotación de minas y canteras y para obras de construcción', seccion: 'C' },
  { codigo: '2825', descripcion: 'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco', seccion: 'C' },
  { codigo: '2826', descripcion: 'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros', seccion: 'C' },
  { codigo: '2829', descripcion: 'Fabricación de otros tipos de maquinaria y equipo de uso especial n.c.p.', seccion: 'C' },
  { codigo: '2910', descripcion: 'Fabricación de vehículos automotores y sus motores', seccion: 'C' },
  { codigo: '2920', descripcion: 'Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques', seccion: 'C' },
  { codigo: '2930', descripcion: 'Fabricación de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores', seccion: 'C' },
  { codigo: '3011', descripcion: 'Construcción de barcos y de estructuras flotantes', seccion: 'C' },
  { codigo: '3012', descripcion: 'Construcción de embarcaciones de recreo y deporte', seccion: 'C' },
  { codigo: '3020', descripcion: 'Fabricación de locomotoras y de material rodante para ferrocarriles', seccion: 'C' },
  { codigo: '3030', descripcion: 'Fabricación de aeronaves, naves espaciales y de maquinaria conexa', seccion: 'C' },
  { codigo: '3040', descripcion: 'Fabricación de vehículos militares de combate', seccion: 'C' },
  { codigo: '3091', descripcion: 'Fabricación de motocicletas', seccion: 'C' },
  { codigo: '3092', descripcion: 'Fabricación de bicicletas y de sillas de ruedas para personas con discapacidad', seccion: 'C' },
  { codigo: '3099', descripcion: 'Fabricación de otros tipos de equipo de transporte n.c.p.', seccion: 'C' },
  { codigo: '3110', descripcion: 'Fabricación de muebles', seccion: 'C' },
  { codigo: '3120', descripcion: 'Fabricación de colchones y somieres', seccion: 'C' },
  { codigo: '3210', descripcion: 'Fabricación de joyas, bisutería y artículos conexos', seccion: 'C' },
  { codigo: '3220', descripcion: 'Fabricación de instrumentos musicales', seccion: 'C' },
  { codigo: '3230', descripcion: 'Fabricación de artículos y equipo para la práctica del deporte', seccion: 'C' },
  { codigo: '3240', descripcion: 'Fabricación de juegos, juguetes y rompecabezas', seccion: 'C' },
  { codigo: '3250', descripcion: 'Fabricación de instrumentos, aparatos y materiales médicos y odontológicos (incluido mobiliario)', seccion: 'C' },
  { codigo: '3290', descripcion: 'Otras industrias manufactureras n.c.p.', seccion: 'C' },
  { codigo: '3311', descripcion: 'Mantenimiento y reparación especializado de productos elaborados en metal', seccion: 'C' },
  { codigo: '3312', descripcion: 'Mantenimiento y reparación especializado de maquinaria y equipo', seccion: 'C' },
  { codigo: '3313', descripcion: 'Mantenimiento y reparación especializado de equipo electrónico y óptico', seccion: 'C' },
  { codigo: '3314', descripcion: 'Mantenimiento y reparación especializado de equipo eléctrico', seccion: 'C' },
  { codigo: '3315', descripcion: 'Mantenimiento y reparación especializado de equipo de transporte, excepto los vehículos automotores, motocicletas y bicicletas', seccion: 'C' },
  { codigo: '3319', descripcion: 'Mantenimiento y reparación de otros tipos de equipos y sus componentes n.c.p.', seccion: 'C' },
  { codigo: '3320', descripcion: 'Instalación especializada de maquinaria y equipo industrial', seccion: 'C' },
  { codigo: '3511', descripcion: 'Generación de energía eléctrica', seccion: 'D' },
  { codigo: '3512', descripcion: 'Transmisión de energía eléctrica', seccion: 'D' },
  { codigo: '3513', descripcion: 'Distribución de energía eléctrica', seccion: 'D' },
  { codigo: '3514', descripcion: 'Comercialización de energía eléctrica', seccion: 'D' },
  { codigo: '3520', descripcion: 'Producción de gas; distribución de combustibles gaseosos por tuberías', seccion: 'D' },
  { codigo: '3530', descripcion: 'Suministro de vapor y aire acondicionado', seccion: 'D' },
  { codigo: '3600', descripcion: 'Captación, tratamiento y distribución de agua', seccion: 'E' },
  { codigo: '3700', descripcion: 'Evacuación y tratamiento de aguas residuales', seccion: 'E' },
  { codigo: '3811', descripcion: 'Recolección de desechos no peligrosos', seccion: 'E' },
  { codigo: '3812', descripcion: 'Recolección de desechos peligrosos', seccion: 'E' },
  { codigo: '3821', descripcion: 'Tratamiento y disposición de desechos no peligrosos', seccion: 'E' },
  { codigo: '3822', descripcion: 'Tratamiento y disposición de desechos peligrosos', seccion: 'E' },
  { codigo: '3830', descripcion: 'Recuperación de materiales', seccion: 'E' },
  { codigo: '3900', descripcion: 'Actividades de saneamiento ambiental y otros servicios de gestión de desechos', seccion: 'E' },
  { codigo: '4111', descripcion: 'Construcción de edificios residenciales', seccion: 'F' },
  { codigo: '4112', descripcion: 'Construcción de edificios no residenciales', seccion: 'F' },
  { codigo: '4210', descripcion: 'Construcción de carreteras y vías de ferrocarril', seccion: 'F' },
  { codigo: '4220', descripcion: 'Construcción de proyectos de servicio público', seccion: 'F' },
  { codigo: '4290', descripcion: 'Construcción de otras obras de ingeniería civil', seccion: 'F' },
  { codigo: '4311', descripcion: 'Demolición', seccion: 'F' },
  { codigo: '4312', descripcion: 'Preparación del terreno', seccion: 'F' },
  { codigo: '4321', descripcion: 'Instalaciones eléctricas', seccion: 'F' },
  { codigo: '4322', descripcion: 'Instalaciones de fontanería, calefacción y aire acondicionado', seccion: 'F' },
  { codigo: '4329', descripcion: 'Otras instalaciones especializadas', seccion: 'F' },
  { codigo: '4330', descripcion: 'Terminación y acabado de edificios y obras de ingeniería civil', seccion: 'F' },
  { codigo: '4390', descripcion: 'Otras actividades especializadas para la construcción de edificios y obras de ingeniería civil', seccion: 'F' },
  { codigo: '4511', descripcion: 'Comercio de vehículos automotores nuevos', seccion: 'G' },
  { codigo: '4512', descripcion: 'Comercio de vehículos automotores usados', seccion: 'G' },
  { codigo: '4520', descripcion: 'Mantenimiento y reparación de vehículos automotores', seccion: 'G' },
  { codigo: '4530', descripcion: 'Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores', seccion: 'G' },
  { codigo: '4541', descripcion: 'Comercio de motocicletas y de sus partes, piezas y accesorios', seccion: 'G' },
  { codigo: '4542', descripcion: 'Mantenimiento y reparación de motocicletas y de sus partes y piezas', seccion: 'G' },
  { codigo: '4610', descripcion: 'Comercio al por mayor a cambio de una retribución o por contrata', seccion: 'G' },
  { codigo: '4620', descripcion: 'Comercio al por mayor de materias primas agropecuarias; animales vivos', seccion: 'G' },
  { codigo: '4631', descripcion: 'Comercio al por mayor de productos alimenticios', seccion: 'G' },
  { codigo: '4632', descripcion: 'Comercio al por mayor de bebidas y tabaco', seccion: 'G' },
  { codigo: '4641', descripcion: 'Comercio al por mayor de productos textiles, productos confeccionados para uso doméstico', seccion: 'G' },
  { codigo: '4642', descripcion: 'Comercio al por mayor de prendas de vestir', seccion: 'G' },
  { codigo: '4643', descripcion: 'Comercio al por mayor de calzado', seccion: 'G' },
  { codigo: '4644', descripcion: 'Comercio al por mayor de aparatos y equipo de uso doméstico', seccion: 'G' },
  { codigo: '4645', descripcion: 'Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos y de tocador', seccion: 'G' },
  { codigo: '4649', descripcion: 'Comercio al por mayor de otros utensilios domésticos n.c.p.', seccion: 'G' },
  { codigo: '4651', descripcion: 'Comercio al por mayor de computadores, equipo periférico y programas de informática', seccion: 'G' },
  { codigo: '4652', descripcion: 'Comercio al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones', seccion: 'G' },
  { codigo: '4653', descripcion: 'Comercio al por mayor de maquinaria y equipo agropecuarios', seccion: 'G' },
  { codigo: '4659', descripcion: 'Comercio al por mayor de otros tipos de maquinaria y equipo n.c.p.', seccion: 'G' },
  { codigo: '4661', descripcion: 'Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y productos conexos', seccion: 'G' },
  { codigo: '4662', descripcion: 'Comercio al por mayor de metales y productos metalíferos', seccion: 'G' },
  { codigo: '4663', descripcion: 'Comercio al por mayor de materiales de construcción, artículos de ferretería, pinturas, productos de vidrio, equipo y materiales de fontanería y calefacción', seccion: 'G' },
  { codigo: '4664', descripcion: 'Comercio al por mayor de productos químicos básicos, cauchos y plásticos en formas primarias y productos químicos de uso agropecuario', seccion: 'G' },
  { codigo: '4665', descripcion: 'Comercio al por mayor de desperdicios, desechos y chatarra', seccion: 'G' },
  { codigo: '4669', descripcion: 'Comercio al por mayor de otros productos n.c.p.', seccion: 'G' },
  { codigo: '4690', descripcion: 'Comercio al por mayor no especializado', seccion: 'G' },
  { codigo: '4711', descripcion: 'Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente por alimentos, bebidas (alcohólicas y no alcohólicas) o tabaco', seccion: 'G' },
  { codigo: '4719', descripcion: 'Comercio al por menor en establecimientos no especializados, con surtido compuesto principalmente por productos diferentes de alimentos (víveres en general), bebidas (alcohólicas y no alcohólicas) y tabaco', seccion: 'G' },
  { codigo: '4721', descripcion: 'Comercio al por menor de productos agrícolas para el consumo en establecimientos especializados', seccion: 'G' },
  { codigo: '4722', descripcion: 'Comercio al por menor de leche, productos lácteos y huevos, en establecimientos especializados', seccion: 'G' },
  { codigo: '4723', descripcion: 'Comercio al por menor de carnes (incluye aves de corral), productos cárnicos, pescados y productos de mar, en establecimientos especializados', seccion: 'G' },
  { codigo: '4724', descripcion: 'Comercio al por menor de bebidas y productos del tabaco, en establecimientos especializados', seccion: 'G' },
  { codigo: '4729', descripcion: 'Comercio al por menor de otros productos alimenticios n.c.p., en establecimientos especializados', seccion: 'G' },
  { codigo: '4731', descripcion: 'Comercio al por menor de combustible para automotores', seccion: 'G' },
  { codigo: '4732', descripcion: 'Comercio al por menor de lubricantes (aceites, grasas), aditivos y productos de limpieza para vehículos automotores', seccion: 'G' },
  { codigo: '4741', descripcion: 'Comercio al por menor de computadores, equipos periféricos, programas de informática y equipos de telecomunicaciones en establecimientos especializados', seccion: 'G' },
  { codigo: '4742', descripcion: 'Comercio al por menor de equipos y aparatos de sonido y de video, en establecimientos especializados', seccion: 'G' },
  { codigo: '4751', descripcion: 'Comercio al por menor de productos textiles en establecimientos especializados', seccion: 'G' },
  { codigo: '4752', descripcion: 'Comercio al por menor de artículos de ferretería, pinturas y productos de vidrio en establecimientos especializados', seccion: 'G' },
  { codigo: '4753', descripcion: 'Comercio al por menor de tapices, alfombras y cubrimientos para paredes y pisos en establecimientos especializados.', seccion: 'G' },
  { codigo: '4754', descripcion: 'Comercio al por menor de electrodomésticos y gasodomésticos, muebles y equipos de iluminación en establecimientos especializados', seccion: 'G' },
  { codigo: '4755', descripcion: 'Comercio al por menor de artículos y utensilios de uso doméstico en establecimientos especializados', seccion: 'G' },
  { codigo: '4759', descripcion: 'Comercio al por menor de otros artículos domésticos en establecimientos especializados', seccion: 'G' },
  { codigo: '4761', descripcion: 'Comercio al por menor de libros, periódicos, materiales y artículos de papelería y escritorio, en establecimientos especializados', seccion: 'G' },
  { codigo: '4762', descripcion: 'Comercio al por menor de artículos deportivos, en establecimientos especializados', seccion: 'G' },
  { codigo: '4769', descripcion: 'Comercio al por menor de otros artículos culturales y de entretenimiento n.c.p. en establecimientos especializados', seccion: 'G' },
  { codigo: '4771', descripcion: 'Comercio al por menor de prendas de vestir y sus accesorios (incluye artículos de piel) en establecimientos especializados', seccion: 'G' },
  { codigo: '4772', descripcion: 'Comercio al por meno r de todo tipo de calzado y artículos de cuero y sucedáneos del cuero en establecimientos especializados.', seccion: 'G' },
  { codigo: '4773', descripcion: 'Comercio al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador en establecimientos especializados', seccion: 'G' },
  { codigo: '4774', descripcion: 'Comercio al por menor de otros productos nuevos en establecimientos especializados', seccion: 'G' },
  { codigo: '4775', descripcion: 'Comercio al por menor de artículos de segunda mano', seccion: 'G' },
  { codigo: '4781', descripcion: 'Comercio al por menor de alimentos, bebidas y taba co, en puestos de venta móviles', seccion: 'G' },
  { codigo: '4782', descripcion: 'Comercio al por menor de productos textiles, prendas de vestir y calzado, en puestos de venta móviles', seccion: 'G' },
  { codigo: '4789', descripcion: 'Comercio al por menor de otros productos en puestos de venta móviles', seccion: 'G' },
  { codigo: '4791', descripcion: 'Comercio al por menor realizado a través de Internet', seccion: 'G' },
  { codigo: '4792', descripcion: 'Comercio al por menor realizado a través de casas de venta o por correo', seccion: 'G' },
  { codigo: '4799', descripcion: 'Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados.', seccion: 'G' },
  { codigo: '4911', descripcion: 'Transporte férreo de pasajeros', seccion: 'H' },
  { codigo: '4912', descripcion: 'Transporte férreo de carga', seccion: 'H' },
  { codigo: '4921', descripcion: 'Transporte de pasajeros', seccion: 'H' },
  { codigo: '4922', descripcion: 'Transporte mixto', seccion: 'H' },
  { codigo: '4923', descripcion: 'Transporte de carga por carretera', seccion: 'H' },
  { codigo: '4930', descripcion: 'Transporte por tuberías', seccion: 'H' },
  { codigo: '5011', descripcion: 'Transporte de pasajeros marítimo y de cabotaje', seccion: 'H' },
  { codigo: '5012', descripcion: 'Transporte de carga marítimo y de cabotaje', seccion: 'H' },
  { codigo: '5021', descripcion: 'Transporte fluvial de pasajeros', seccion: 'H' },
  { codigo: '5022', descripcion: 'Transporte fluvial de carga', seccion: 'H' },
  { codigo: '5111', descripcion: 'Transporte aéreo nacional de pasajeros', seccion: 'H' },
  { codigo: '5112', descripcion: 'Transporte aéreo internacional de pasajeros', seccion: 'H' },
  { codigo: '5121', descripcion: 'Transporte aéreo nacional de carga', seccion: 'H' },
  { codigo: '5122', descripcion: 'Transporte aéreo internacional de carga', seccion: 'H' },
  { codigo: '5210', descripcion: 'Almacenamiento y depósito', seccion: 'H' },
  { codigo: '5221', descripcion: 'Actividades de estaciones, vías y servicios complementarios para el transporte terrestre', seccion: 'H' },
  { codigo: '5222', descripcion: 'Actividades de puertos y servicios complementarios para el transporte acuático', seccion: 'H' },
  { codigo: '5223', descripcion: 'Actividades de aeropuertos, servicios de navegación aérea y demás actividades conexas al transporte aéreo', seccion: 'H' },
  { codigo: '5224', descripcion: 'Manipulación de carga', seccion: 'H' },
  { codigo: '5229', descripcion: 'Otras actividades complementarias al transporte', seccion: 'H' },
  { codigo: '5310', descripcion: 'Actividades postales nacionales', seccion: 'H' },
  { codigo: '5320', descripcion: 'Actividades de mensajería', seccion: 'H' },
  { codigo: '5511', descripcion: 'Alojamiento en hoteles', seccion: 'I' },
  { codigo: '5512', descripcion: 'Alojamiento en apartahoteles', seccion: 'I' },
  { codigo: '5513', descripcion: 'Alojamiento en centros vacacionales', seccion: 'I' },
  { codigo: '5514', descripcion: 'Alojamiento rural', seccion: 'I' },
  { codigo: '5519', descripcion: 'Otros tipos de alojamientos para visitantes', seccion: 'I' },
  { codigo: '5520', descripcion: 'Actividades de zonas de camping y parques para vehículos recreacionales', seccion: 'I' },
  { codigo: '5530', descripcion: 'Servicio de estancia por horas', seccion: 'I' },
  { codigo: '5590', descripcion: 'Otros tipos de alojamiento n.c.p.', seccion: 'I' },
  { codigo: '5611', descripcion: 'Expendio a la mesa de comidas preparadas', seccion: 'I' },
  { codigo: '5612', descripcion: 'Expendio por autoservicio de comidas preparadas', seccion: 'I' },
  { codigo: '5613', descripcion: 'Expendio de comidas preparadas en cafeterías', seccion: 'I' },
  { codigo: '5619', descripcion: 'Otros tipos de expendio de comidas preparadas n.c.p.', seccion: 'I' },
  { codigo: '5621', descripcion: 'Catering para eventos', seccion: 'I' },
  { codigo: '5629', descripcion: 'Actividades de otros servicios de comidas', seccion: 'I' },
  { codigo: '5630', descripcion: 'Expendio de bebidas alcohólicas para el consumo dentro del establecimiento', seccion: 'I' },
  { codigo: '5811', descripcion: 'Edición de libros', seccion: 'J' },
  { codigo: '5812', descripcion: 'Edición de directorios y listas de correo', seccion: 'J' },
  { codigo: '5813', descripcion: 'Edición de periódicos, revistas y otras publicaciones periódicas', seccion: 'J' },
  { codigo: '5819', descripcion: 'Otros trabajos de edición', seccion: 'J' },
  { codigo: '5820', descripcion: 'Edición de programas de informática (software)', seccion: 'J' },
  { codigo: '5911', descripcion: 'Actividades de producción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión', seccion: 'J' },
  { codigo: '5912', descripcion: 'Actividades de postproducción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión', seccion: 'J' },
  { codigo: '5913', descripcion: 'Actividades de distribución de películas cinematográficas, videos, programas, anuncios y comerciales de televisión', seccion: 'J' },
  { codigo: '5914', descripcion: 'Actividades de exhibición de películas cinematográficas y videos', seccion: 'J' },
  { codigo: '5920', descripcion: 'Actividades de grabación de sonido y edición de música', seccion: 'J' },
  { codigo: '6010', descripcion: 'Actividades de programación y transmisión en el servicio de radiodifusión sonora', seccion: 'J' },
  { codigo: '6020', descripcion: 'Actividades de programación y transmisión de televisión', seccion: 'J' },
  { codigo: '6110', descripcion: 'Actividades de telecomunicaciones alámbricas', seccion: 'J' },
  { codigo: '6120', descripcion: 'Actividades de telecomunicaciones inalámbricas', seccion: 'J' },
  { codigo: '6130', descripcion: 'Actividades de telecomunicación satelital', seccion: 'J' },
  { codigo: '6190', descripcion: 'Otras actividades de telecomunicaciones', seccion: 'J' },
  { codigo: '6201', descripcion: 'Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas)', seccion: 'J' },
  { codigo: '6202', descripcion: 'Actividades de consultoría informática y actividades de administración de instalaciones informáticas', seccion: 'J' },
  { codigo: '6209', descripcion: 'Otras actividades de tecnologías de información y actividades de servicios informáticos', seccion: 'J' },
  { codigo: '6311', descripcion: 'Procesamiento de datos, alojamiento (hosting) y actividades relacionadas', seccion: 'J' },
  { codigo: '6312', descripcion: 'Portales web', seccion: 'J' },
  { codigo: '6391', descripcion: 'Actividades de agencias de noticias', seccion: 'J' },
  { codigo: '6399', descripcion: 'Otras actividades de servicio de información n.c.p.', seccion: 'J' },
  { codigo: '6411', descripcion: 'Banco Central', seccion: 'K' },
  { codigo: '6412', descripcion: 'Bancos comerciales', seccion: 'K' },
  { codigo: '6421', descripcion: 'Actividades de las corporaciones financieras', seccion: 'K' },
  { codigo: '6422', descripcion: 'Actividades de las compañías de financiamiento', seccion: 'K' },
  { codigo: '6423', descripcion: 'Banca de segundo piso', seccion: 'K' },
  { codigo: '6424', descripcion: 'Actividades de las cooperativas financieras', seccion: 'K' },
  { codigo: '6431', descripcion: 'Fideicomisos, fondos y entidades financieras similares', seccion: 'K' },
  { codigo: '6432', descripcion: 'Fondos de cesantías', seccion: 'K' },
  { codigo: '6491', descripcion: 'Leasing financiero (arrendamiento financiero)', seccion: 'K' },
  { codigo: '6492', descripcion: 'Actividades financieras de fondos de empleados y otras formas asociativas del sector solidario', seccion: 'K' },
  { codigo: '6493', descripcion: 'Actividades de compra de cartera o factoring', seccion: 'K' },
  { codigo: '6494', descripcion: 'Otras actividades de distribución de fondos', seccion: 'K' },
  { codigo: '6495', descripcion: 'Instituciones especiales oficiales', seccion: 'K' },
  { codigo: '6496', descripcion: 'Capitalización', seccion: 'K' },
  { codigo: '6499', descripcion: 'Otras actividades de servicio financiero, excepto las de seguros y pensiones n.c.p.', seccion: 'K' },
  { codigo: '6511', descripcion: 'Seguros generales', seccion: 'K' },
  { codigo: '6512', descripcion: 'Seguros de vida', seccion: 'K' },
  { codigo: '6513', descripcion: 'Reaseguros', seccion: 'K' },
  { codigo: '6515', descripcion: 'Seguros de salud', seccion: 'K' },
  { codigo: '6521', descripcion: 'Servicios de seguros sociales de salud', seccion: 'K' },
  { codigo: '6522', descripcion: 'Servicios de seguros sociales en riesgos laborales', seccion: 'K' },
  { codigo: '6523', descripcion: 'Servicios de seguros sociales en riesgos familia', seccion: 'K' },
  { codigo: '6531', descripcion: 'Régimen de prima media con prestación definida (RPM)', seccion: 'K' },
  { codigo: '6532', descripcion: 'Régimen de ahorro individual con solidaridad (RAIS)', seccion: 'K' },
  { codigo: '6611', descripcion: 'Administración de mercados financieros', seccion: 'K' },
  { codigo: '6612', descripcion: 'Corretaje de valores y de contratos de productos básicos', seccion: 'K' },
  { codigo: '6613', descripcion: 'Otras actividades relacionadas con el mercado de valores', seccion: 'K' },
  { codigo: '6614', descripcion: 'Actividades de las sociedades de intermediación cambiaria y de servicios financieros especiales', seccion: 'K' },
  { codigo: '6615', descripcion: 'Actividades de los profesionales de compra y venta de divisas', seccion: 'K' },
  { codigo: '6619', descripcion: 'Otras actividades auxiliares de las actividades de servicios financieros n.c.p.', seccion: 'K' },
  { codigo: '6621', descripcion: 'Actividades de agentes y corredores de seguros', seccion: 'K' },
  { codigo: '6629', descripcion: 'Evaluación de riesgos y daños, y otras actividades de servicios auxiliares', seccion: 'K' },
  { codigo: '6630', descripcion: 'Actividades de administración de fondos', seccion: 'K' },
  { codigo: '6810', descripcion: 'Actividades inmobiliarias realizadas con bienes propios o arrendados', seccion: 'L' },
  { codigo: '6820', descripcion: 'Actividades inmobiliarias realizadas a cambio de una retribución o por contrata', seccion: 'L' },
  { codigo: '6910', descripcion: 'Actividades jurídicas', seccion: 'M' },
  { codigo: '6920', descripcion: 'Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría tributaria', seccion: 'M' },
  { codigo: '7010', descripcion: 'Actividades de administración empresarial', seccion: 'M' },
  { codigo: '7020', descripcion: 'Actividades de consultaría de gestión', seccion: 'M' },
  { codigo: '7111', descripcion: 'Actividades de arquitectura', seccion: 'M' },
  { codigo: '7112', descripcion: 'Actividades de ingeniería y otras actividades conexas de consultoría técnica', seccion: 'M' },
  { codigo: '7120', descripcion: 'Ensayos y análisis técnicos', seccion: 'M' },
  { codigo: '7210', descripcion: 'Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería', seccion: 'M' },
  { codigo: '7220', descripcion: 'Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades', seccion: 'M' },
  { codigo: '7310', descripcion: 'Publicidad', seccion: 'M' },
  { codigo: '7320', descripcion: 'Estudios de mercado y realización de encuestas de opinión pública', seccion: 'M' },
  { codigo: '7410', descripcion: 'Actividades especializadas de diseño', seccion: 'M' },
  { codigo: '7420', descripcion: 'Actividades de fotografía', seccion: 'M' },
  { codigo: '7490', descripcion: 'Otras actividades profesionales, científicas y técnicas n.c.p.', seccion: 'M' },
  { codigo: '7500', descripcion: 'Actividades veterinarias', seccion: 'M' },
  { codigo: '7710', descripcion: 'Alquiler y arrendamiento de vehículos automotores', seccion: 'N' },
  { codigo: '7721', descripcion: 'Alquiler y arrendamiento de equipo recreativo y deportivo', seccion: 'N' },
  { codigo: '7722', descripcion: 'Alquiler de videos y discos', seccion: 'N' },
  { codigo: '7729', descripcion: 'Alquiler y arrendamiento de otros efectos personales y enseres domésticos n.c.p.', seccion: 'N' },
  { codigo: '7730', descripcion: 'Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles n.c.p.', seccion: 'N' },
  { codigo: '7740', descripcion: 'Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor', seccion: 'N' },
  { codigo: '7810', descripcion: 'Actividades de agencias de gestión y colocación de empleo', seccion: 'N' },
  { codigo: '7820', descripcion: 'Actividades de empresas de servicios temporales', seccion: 'N' },
  { codigo: '7830', descripcion: 'Otras actividades de provisión de talento humano', seccion: 'N' },
  { codigo: '7911', descripcion: 'Actividades de las agencias de viaje', seccion: 'N' },
  { codigo: '7912', descripcion: 'Actividades de operadores turísticos', seccion: 'N' },
  { codigo: '7990', descripcion: 'Otros servicios de reserva y actividades relacionadas', seccion: 'N' },
  { codigo: '8010', descripcion: 'Actividades de seguridad privada', seccion: 'N' },
  { codigo: '8020', descripcion: 'Actividades de servicios de sistemas de seguridad', seccion: 'N' },
  { codigo: '8030', descripcion: 'Actividades de detectives e investigadores privados', seccion: 'N' },
  { codigo: '8110', descripcion: 'Actividades combinadas de apoyo a instalaciones', seccion: 'N' },
  { codigo: '8121', descripcion: 'Limpieza general interior de edificios', seccion: 'N' },
  { codigo: '8129', descripcion: 'Otras actividades de limpieza de edificios e instalaciones industriales', seccion: 'N' },
  { codigo: '8130', descripcion: 'Actividades de paisajismo y servicios de mantenimiento conexos', seccion: 'N' },
  { codigo: '8211', descripcion: 'Actividades combinadas de servicios administrativos de oficina', seccion: 'N' },
  { codigo: '8219', descripcion: 'Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficina', seccion: 'N' },
  { codigo: '8220', descripcion: 'Actividades de centros de llamadas (Call center)', seccion: 'N' },
  { codigo: '8230', descripcion: 'Organización de convenciones y eventos comerciales', seccion: 'N' },
  { codigo: '8291', descripcion: 'Actividades de agencias de cobranza y oficinas de calificación crediticia', seccion: 'N' },
  { codigo: '8292', descripcion: 'Actividades de envase y empaque', seccion: 'N' },
  { codigo: '8299', descripcion: 'Otras actividades de servicio de apoyo a las empresas n.c.p.', seccion: 'N' },
  { codigo: '8411', descripcion: 'Actividades legislativas de la administración pública', seccion: 'O' },
  { codigo: '8412', descripcion: 'Actividades ejecutivas de la administración pública', seccion: 'O' },
  { codigo: '8413', descripcion: 'Regulación de las actividades de organismos que presta n servicios de salud, educativos, culturales y otros servicios sociales, excepto servicios de seguridad social', seccion: 'O' },
  { codigo: '8414', descripcion: 'Actividades reguladoras y facilitadoras de la actividad económica', seccion: 'O' },
  { codigo: '8415', descripcion: 'Actividades de los órganos de control y otras instituciones', seccion: 'O' },
  { codigo: '8421', descripcion: 'Relaciones exteriores', seccion: 'O' },
  { codigo: '8422', descripcion: 'Actividades de defensa', seccion: 'O' },
  { codigo: '8423', descripcion: 'Orden público y actividades de seguridad', seccion: 'O' },
  { codigo: '8424', descripcion: 'Administración de justicia', seccion: 'O' },
  { codigo: '8430', descripcion: 'Actividades de planes de Seguridad Social de afiliación obligatoria', seccion: 'O' },
  { codigo: '8511', descripcion: 'Educación de la primera infancia', seccion: 'P' },
  { codigo: '8512', descripcion: 'Educación preescolar', seccion: 'P' },
  { codigo: '8513', descripcion: 'Educación básica primaria', seccion: 'P' },
  { codigo: '8521', descripcion: 'Educación básica secundaria', seccion: 'P' },
  { codigo: '8522', descripcion: 'Educación media académica', seccion: 'P' },
  { codigo: '8523', descripcion: 'Educación media técnica', seccion: 'P' },
  { codigo: '8530', descripcion: 'Establecimientos que combinan diferentes niveles de educación', seccion: 'P' },
  { codigo: '8541', descripcion: 'Educación técnica profesional', seccion: 'P' },
  { codigo: '8542', descripcion: 'Educación tecnológica', seccion: 'P' },
  { codigo: '8543', descripcion: 'Educación de instituciones universitarias o de escuelas tecnológicas', seccion: 'P' },
  { codigo: '8544', descripcion: 'Educación de universidades', seccion: 'P' },
  { codigo: '8551', descripcion: 'Formación para el trabajo', seccion: 'P' },
  { codigo: '8552', descripcion: 'Enseñanza deportiva y recreativa', seccion: 'P' },
  { codigo: '8553', descripcion: 'Enseñanza cultural', seccion: 'P' },
  { codigo: '8559', descripcion: 'Otros tipos de educación n.c.p.', seccion: 'P' },
  { codigo: '8560', descripcion: 'Actividades de apoyo a la educación', seccion: 'P' },
  { codigo: '8610', descripcion: 'Actividades de hospitales y clínicas, con internación', seccion: 'Q' },
  { codigo: '8621', descripcion: 'Actividades de la práctica médica, sin internación', seccion: 'Q' },
  { codigo: '8622', descripcion: 'Actividades de la práctica odontológica', seccion: 'Q' },
  { codigo: '8691', descripcion: 'Actividades de apoyo diagnóstico', seccion: 'Q' },
  { codigo: '8692', descripcion: 'Actividades de apoyo terapéutico', seccion: 'Q' },
  { codigo: '8699', descripcion: 'Otras actividades de atención de la salud humana', seccion: 'Q' },
  { codigo: '8710', descripcion: 'Actividades de atención residencial medicalizada de tipo general', seccion: 'Q' },
  { codigo: '8720', descripcion: 'Actividades de atención residencial, para el cuidado de pacientes con retardo mental, enfermedad mental y consumo de sustancias psicoactivas', seccion: 'Q' },
  { codigo: '8730', descripcion: 'Actividades de atención en instituciones para el cuidado de personas mayores y/o discapacitadas', seccion: 'Q' },
  { codigo: '8790', descripcion: 'Otras actividades de atención en instituciones con alojamiento', seccion: 'Q' },
  { codigo: '8810', descripcion: 'Actividades de asistencia social sin alojamiento para personas mayores y discapacitadas', seccion: 'Q' },
  { codigo: '8891', descripcion: 'Actividades deguarderías para niños y niñas', seccion: 'Q' },
  { codigo: '8899', descripcion: 'Otras actividades de asistencia social sin alojamiento n.c.p.', seccion: 'Q' },
  { codigo: '9001', descripcion: 'Creación literaria', seccion: 'R' },
  { codigo: '9002', descripcion: 'Creación musical', seccion: 'R' },
  { codigo: '9003', descripcion: 'Creación teatral', seccion: 'R' },
  { codigo: '9004', descripcion: 'Creación audiovisual', seccion: 'R' },
  { codigo: '9005', descripcion: 'Artes plásticas y visuales', seccion: 'R' },
  { codigo: '9006', descripcion: 'Actividades teatrales', seccion: 'R' },
  { codigo: '9007', descripcion: 'Actividades de espectáculos musicales en vivo', seccion: 'R' },
  { codigo: '9008', descripcion: 'Otras actividades de espectáculos en vivo n.c.p.', seccion: 'R' },
  { codigo: '9101', descripcion: 'Actividades de Bibliotecas y archivos', seccion: 'R' },
  { codigo: '9102', descripcion: 'Actividades y funcionamiento de museos, conservación de edificios y sitios históricos', seccion: 'R' },
  { codigo: '9103', descripcion: 'Actividades de jardines botánicos, zoológicos y reservas naturales', seccion: 'R' },
  { codigo: '9200', descripcion: 'Actividades de juegos de azar y apuestas', seccion: 'R' },
  { codigo: '9311', descripcion: 'Gestión de instalaciones deportivas', seccion: 'R' },
  { codigo: '9312', descripcion: 'Actividades de clubes deportivos', seccion: 'R' },
  { codigo: '9319', descripcion: 'Otras actividades deportivas', seccion: 'R' },
  { codigo: '9321', descripcion: 'Actividades de parques de atracciones y parques temáticos', seccion: 'R' },
  { codigo: '9329', descripcion: 'Otras actividades recreativas y de esparcimiento n.c.p.', seccion: 'R' },
  { codigo: '9411', descripcion: 'Actividades de asociaciones empresariales y de empleadores', seccion: 'S' },
  { codigo: '9412', descripcion: 'Actividades de asociaciones profesionales', seccion: 'S' },
  { codigo: '9420', descripcion: 'Actividades de sindicatos de empleados', seccion: 'S' },
  { codigo: '9491', descripcion: 'Actividades de asociaciones religiosas', seccion: 'S' },
  { codigo: '9492', descripcion: 'Actividades de asociaciones políticas', seccion: 'S' },
  { codigo: '9499', descripcion: 'Actividades de otras asociaciones n.c.p.', seccion: 'S' },
  { codigo: '9511', descripcion: 'Mantenimiento y reparación de computadores y de equipo periférico', seccion: 'S' },
  { codigo: '9512', descripcion: 'Mantenimiento y reparación de equipos de comunicación', seccion: 'S' },
  { codigo: '9521', descripcion: 'Mantenimiento y reparación de aparatos electrónicos de consumo', seccion: 'S' },
  { codigo: '9522', descripcion: 'Mantenimiento y reparación de aparatos y equipos domésticos y de jardinería', seccion: 'S' },
  { codigo: '9523', descripcion: 'Reparación de calzado y artículos de cuero', seccion: 'S' },
  { codigo: '9524', descripcion: 'Reparación de muebles y accesorios para el hogar', seccion: 'S' },
  { codigo: '9529', descripcion: 'Mantenimiento y reparación de otros efectos personales y enseres domésticos', seccion: 'S' },
  { codigo: '9601', descripcion: 'Lavado y limpieza, incluso la limpieza en seco, de productos textiles y de piel', seccion: 'S' },
  { codigo: '9602', descripcion: 'Peluquería y otros tratamientos de belleza', seccion: 'S' },
  { codigo: '9603', descripcion: 'Pompas fúnebres y actividades relacionadas', seccion: 'S' },
  { codigo: '9609', descripcion: 'Otras actividades de servicios personales n.c.p.', seccion: 'S' },
  { codigo: '9700', descripcion: 'Actividades de los hogares individuales como empleadores de personal doméstico', seccion: 'T' },
  { codigo: '9810', descripcion: 'Actividades no diferenciadas de los hogares individuales como productores de bienes para uso propio', seccion: 'T' },
  { codigo: '9820', descripcion: 'Actividades no diferenciadas de los hogares individuales como productores de servicios para uso propio', seccion: 'T' },
  { codigo: '9900', descripcion: 'Actividades de organizaciones y entidades extraterritoriales', seccion: 'U' },
];
